name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@6d58852c35a27e6034745c5d0bc373d739014f7f # v3
        with:
          apiToken: ${{ dyiP5zstuMebQZhF5xb8BxyLfE4fbyjTQfRWqqjb }}
          accountId: ${{ 5bb1736522a22612c66ce66b30f0f5e5 }}
